Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.18/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.18/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/soumyajitghosh/suicide_detection/src/suicide_detection/training/train.py", line 517, in <module>
    main()
  File "/Users/soumyajitghosh/suicide_detection/src/suicide_detection/training/train.py", line 498, in main
    run_bert(train, val, test, output_dir, logger, model_name=args.bert_model_name)
  File "/Users/soumyajitghosh/suicide_detection/src/suicide_detection/training/train.py", line 316, in run_bert
    args = TrainingArguments(
TypeError: TrainingArguments.__init__() got an unexpected keyword argument 'evaluation_strategy'
